USE [master]
GO

/****** Object:  Database [CHEVEUX]    Script Date: 2018/06/06 15:24:13 ******/
CREATE DATABASE [CHEVEUX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CHEVEUX', FILENAME = N'F:\Google Drive\Visual Studio\Cheveux\CHEVEUX.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CHEVEUX_log', FILENAME = N'F:\Google Drive\Visual Studio\Cheveux\CHEVEUX_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CHEVEUX] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CHEVEUX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CHEVEUX] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CHEVEUX] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CHEVEUX] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CHEVEUX] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CHEVEUX] SET ARITHABORT OFF 
GO

ALTER DATABASE [CHEVEUX] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CHEVEUX] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CHEVEUX] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CHEVEUX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CHEVEUX] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CHEVEUX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CHEVEUX] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CHEVEUX] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CHEVEUX] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CHEVEUX] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CHEVEUX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CHEVEUX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CHEVEUX] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CHEVEUX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CHEVEUX] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CHEVEUX] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CHEVEUX] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CHEVEUX] SET RECOVERY FULL 
GO

ALTER DATABASE [CHEVEUX] SET  MULTI_USER 
GO

ALTER DATABASE [CHEVEUX] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CHEVEUX] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CHEVEUX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CHEVEUX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CHEVEUX] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CHEVEUX] SET QUERY_STORE = OFF
GO

USE [CHEVEUX]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CHEVEUX] SET  READ_WRITE 
GO

