
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE SP_AddBraidService
	@ProductID nchar(10),		
	@LengthID nchar(10),
	@StyleID nchar(10),
	@WidthID nchar(10)
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			INSERT INTO BRAID_SERVICE(ServiceID, StyleID, LengthID, WidthID)
			VALUES(@ProductID, @StyleID, @LengthID, @WidthID)
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
	END CATCH

END
GO
