
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

alter  PROCEDURE SP_AddToBookingService
	@BookingID nchar(10),
	@ServiceID nchar(10)
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION
			INSERT INTO BookingService(BookingID, ServiceID)
			VALUES(@BookingID, @ServiceID)
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
	END CATCH

END
GO
